# Basic customization for tidb-cluster chart that is suitable for a AKS cluster
timezone: UTC

pd:
  annotations:
    tidb.pingcap.com/sysctl-init: "true"
  podSecurityContext:
    sysctls:
    - name: net.core.somaxconn
      value: "32768"
  storageClassName: "managed-premium"
tikv:
  annotations:
    tidb.pingcap.com/sysctl-init: "true"
  podSecurityContext:
    sysctls:
    - name: net.core.somaxconn
      value: "32768"
  storageClassName: "managed-premium"
tidb:
  annotations:
    tidb.pingcap.com/sysctl-init: "true"
  podSecurityContext:
    sysctls:
    - name: net.core.somaxconn
      value: "32768"
    - name: net.ipv4.tcp_keepalive_intvl
      value: "75"
    - name: net.ipv4.tcp_keepalive_time
      value: "300"
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      cloud.google.com/load-balancer-type: "Internal"
  separateSlowLog: true
monitor:
  storageClassName: "managed-premium"
  persistent: true
  grafana:
    config:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    service:
      type: LoadBalancer
